# 运行在 Velocity 上时的语言配置

# 不要更改本设置，否则会造成配置重置，后果自负。
# 更新新的插件版本也会导致配置重置。请务必提前备份配置文件
version = "@VERSION@"

# 语言名称
# 将会显示在日志和各种提示中
name = "简体中文"

# 显示模式
mode = ""

# 日志提示类
[logs]
loading = "插件正在启动 ~ ~ ~"
command-loading = "正在注册 命令 ……"
database-loading = "正在加载 数据库 ……"
listener-loading = "正在注册 监听器 ……"
channel-loading = "正在注册 插件消息通道 ……"

author = "插件作者："
debug = "请注意！当前已启用 Debug 模式。"

thanks = "感谢您使用本插件！"
end = "===加载完毕==="
website = "本插件是开源的。Github ："

reload = "插件配置文件已重载。"

# 命令类
[commands]
root = "========VelocityTitle========\n"
parameter-less = "缺少必要的参数！"
create-success = "创建成功！"
console = "控制台不能执行该指令！"

# 命令帮助类
[commands.helps]
open = "使用 /vt help 打开帮助页面"
create-prefix = "/vt create prefix [称号ID] [显示内容（可使用&）]  设置前缀"
create-suffix = "/vt create suffix [称号ID] [显示内容（可使用&）]  设置后缀"


# 数据库类
[database]
embedded = "[数据库] 正在加载嵌入式（Embedded）数据库……"
server = "[数据库] 正在加载服务器模式（Server）数据库……"
other = "[数据库] 无法识别数据库模式！正在加载默认的嵌入式（Embedded）数据库……"
timeout = "[数据库] 链接超时！"
failed = "[数据库] 无法链接到数据库！"
failed-operate = "[数据库] 数据库在操作时出现问题！"
