# 运行在 Velocity 上时的语言配置

# 不要更改本设置，否则会造成配置重置，后果自负。
# 更新新的插件版本也会导致配置重置。请务必提前备份配置文件
version = "@VERSION@"

# 语言名称
# 将会显示在日志和各种提示中
name = "简体中文"

# 显示模式
mode = ""

# 日志提示类
[logs]
loading = "插件正在启动 ~ ~ ~"
command-loading = "正在注册 命令 ……"
database-loading = "正在加载 数据库 ……"
listener-loading = "正在注册 监听器 ……"
channel-loading = "正在注册 插件消息通道 ……"

author = "插件作者："
debug = "请注意！当前已启用 Debug 模式。"

thanks = "感谢您使用本插件！"
end = "===加载完毕==="
website = "本插件是开源的。Github ："

reload = "插件配置文件已重载。"

# 命令类
[commands]
head = "==== VelocityTitle v{} ====&r"

# 短提示前缀
prefix = "&f[&bVT&f]&r "

help = "&9使用 &a/vt help &9来查看可用的命令&r"
param = "&9参数： &r"

title = "&btitle 子命令：&f（/vt title ...）&r"
player = "&bpalyer 子命令：&f（/vt player ...）&r"
database = "&bdatabase 子命令：&f（/vt database ...）&r"

[commands.titles]
create = "&btitle create &9- &b创建一个称号&r"
create-p = " &b- &7<&fname&7> &9-> &f称号的 ID，具有唯一性 &r\n &b- &7<&fdisplay&7> &9-> &f称号对外展示的形式，可以使用中文和颜色代码 &r\n &b- &7[&fdescription&7] &9-> &f 称号的描述 &r"

edit = "&btitle edit &9- &b编辑一个称号&r"
edit-p = " &b- &7<&fname&7> &9-> &f称号的 ID，具有唯一性 &r\n &b- &7(&fdisplay|description&7) &9-> &f任意选择一个进行编辑 &r\n &b- &7<&fdisplay/description&7> &9-> &f 将前面选定的项设为此值 &r"

delete = "&btitle delete &9- &b删除一个称号&r"
delete-p = " &b- &7<&fname&7> &9-> &f称号的 ID，具有唯一性 &r"

list = "&btitle list &9- &b列出已知的称号&r"

[commands.tips]


# 数据库类
[database]
embedded = "[数据库] 正在加载嵌入式（Embedded）数据库……"
server = "[数据库] 正在加载服务器模式（Server）数据库……"
other = "[数据库] 无法识别数据库模式！正在加载默认的嵌入式（Embedded）数据库……"
timeout = "[数据库] 链接超时！"
failed = "[数据库] 无法链接到数据库！"
failed-operate = "[数据库] 数据库在操作时出现问题！"
